language: python
python: 3.5

install:
  pip3 install -r requirements.txt

before_script:
  - source ./setup.sh
  - "export FLASK_APP=app/application.py"
  - flask run &

script: python -m unittest discover tests "TEST*"
